vich_uploader:
    db_driver: orm

    mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        baseArtImage:
            uri_prefix: /images/baseArtImage
            upload_destination: '%kernel.project_dir%/public/images/baseArtImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true

    
    
        imageImage:
            uri_prefix: /images/imageImage
            upload_destination: '%kernel.project_dir%/public/images/imageImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
    
    
        logoImage:
            uri_prefix: /images/logoImage
            upload_destination: '%kernel.project_dir%/public/images/logoImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
    
    
        backgroundArtImage:
            uri_prefix: /images/backgroundArtImage
            upload_destination: '%kernel.project_dir%/public/images/backgroundArtImage'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
    
    